# PharmDesk Configuration
# -------------------------------------------------------
# This file is bundled inside the jar as a default template.
# On first launch, it is copied to:
#   C:\ProgramData\PharmDesk\config.properties
# Edit THAT copy in Notepad to change your settings.
# -------------------------------------------------------

pharmacy.name=NOBLE TRADER
pharmacy.address=SHOP 23, MAIN MARKET
pharmacy.phone=03139451041

db.name=wholesale_pharmacy.db

# Set to the exact printer name from Windows Devices & Printers
printer.name=